### ISSUE TITLE
tokens not work 

### ISSUE THREAD

**Issue by godlygamer123** [BlacketWare/Legacy#100]
how do you use these ones they do not seem to be working with javascript:

**Comment by VillainsRule4000** [comment]
These hacks are for Blacket Legacy, which can be located [here](https://legacy.blacket.org).
If you are looking for hacks for the newer Blacket, click [here](https://github.com/BlacketWare/v2).

I just tested it, and this works fine on Legacy.

**Comment by godlygamer123** [comment]
thank you
